apiVersion: appsody.dev/v1beta1
kind: AppsodyApplication
metadata:
  labels:
    image.opencontainers.org/title: stackaa-flight
    stack.appsody.dev/id: java-openliberty
  name: stackaa-flight
  namespace: kabanero
spec:
  applicationImage: stackaa-flight 
  createKnativeService: false
  expose: true
  env:
  - name: USERNAME
    value: admin
  - name: PASSWORD
    value: password
  - name: MONGO_HOST
    value: bphmongo.rtp.raleigh.ibm.com
  - name: SECURE_SERVICE_CALLS
    value: 'true'
  service:
    type: NodePort
    port: 9080
    annotations:
      prometheus.io/scrape: 'true'
  readinessProbe:
    failureThreshold: 12
    httpGet:
      path: /health/ready
      port: 9080
    initialDelaySeconds: 60
    periodSeconds: 2
  livenessProbe:
    failureThreshold: 12
    httpGet:
      path: /health/live
      port: 9080
    initialDelaySeconds: 60
    periodSeconds: 2
  expose: true
  stack: java-openliberty
  version: 1.0.0
